name: user_app
description: A new Flutter project.


publish_to: "none" 

version: 2.0.1+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.2
  shared_preferences:
  toast:
  auto_size_text:
  http:
  carousel_slider: ^3.0.0
  google_fonts:
  flutter_icons:
  intl:
  url_launcher:
  flutter_otp_text_field:
  cached_network_image:
  firebase_core: 
  firebase_auth: 
  flutter_google_places:
  shimmer: ^2.0.0
  socket_io_client: 2.0.0-beta.4-nullsafety.0
  google_maps_flutter:
  geolocator:
  expandable_text:
  dotted_border:
  razorpay_flutter: ^1.2.6
  geocoder:
  share: ^2.0.4
  firebase_messaging: 8.0.0-dev.15
  flutter_local_notifications:
  provider:
  flutter_widget_from_html_core: ^0.6.1+4
  flutter_launcher_icons: "^0.9.0"
  flutter_typeahead:
  step_progress_indicator: 
  syncfusion_flutter_charts:

dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:

  uses-material-design: true


  assets:
    - assets/images/
    - assets/fonts/